"use client";
import HeaderTable from "@/modules/table/components/HeaderTable";
import { useState } from "react";
import ListTable from "@/modules/table/components/ListTable";

export default function MainTable() {
	const [useEscribanos, setEscribanos] = useState([
		{
			id: "1",
			name: "Cy Ganderton",
			position: "Quality Control Specialist",
			company: "Littel, Schaden and Vandervort",
			country: "Canada",
			start_date: "12/16/2020",
			color: "Blue",
		},
		{
			id: "2",
			name: "Hart Hagerty",
			position: "Desktop Support Technician",
			company: "Zemlak, Daniel and Leannon",
			country: "United States",
			start_date: "12/5/2020",
			color: "Purple",
		},
		{
			id: "3",
			name: "Brice Swyre",
			position: "Tax Accountant",
			company: "Carroll Group",
			country: "China",
			start_date: "8/15/2020",
			color: "Red",
		},
		{
			id: "4",
			name: "Marjy Ferencz",
			position: "Office Assistant I",
			company: "Rowe-Schoen",
			country: "Russia",
			start_date: "3/25/2021",
			color: "Crimson",
		},
		{
			id: "5",
			name: "Yancy Tear",
			position: "Community Outreach Specialist",
			company: "Wyman-Ledner",
			country: "Brazil",
			start_date: "5/22/2020",
			color: "Indigo",
		},
		{
			id: "6",
			name: "Irma Vasilik",
			position: "Editor",
			company: "Wiza, Bins and Emard",
			country: "Venezuela",
			start_date: "12/8/2020",
			color: "Purple",
		},
		{
			id: "7",
			name: "Meghann Durtnal",
			position: "Staff Accountant IV",
			company: "Schuster-Schimmel",
			country: "Philippines",
			start_date: "2/17/2021",
			color: "Yellow",
		},
		{
			id: "8",
			name: "Sammy Seston",
			position: "Accountant I",
			company: "Hara, Welch and Keebler",
			country: "Indonesia",
			start_date: "5/23/2020",
			color: "Crimson",
		},
		{
			id: "9",
			name: "Lesya Tinham",
			position: "Safety Technician IV",
			company: "Turner-Kuhlman",
			country: "Philippines",
			start_date: "2/21/2021",
			color: "Maroon",
		},
		{
			id: "10",
			name: "Zaneta Tewkesbury",
			position: "VP Marketing",
			company: "Sauer LLC",
			country: "Chad",
			start_date: "6/23/2020",
			color: "Green",
		},
		{
			id: "11",
			name: "Andy Tipple",
			position: "Librarian",
			company: "Hilpert Group",
			country: "Poland",
			start_date: "7/9/2020",
			color: "Indigo",
		},
		{
			id: "12",
			name: "Sophi Biles",
			position: "Recruiting Manager",
			company: "Gutmann Inc",
			country: "Indonesia",
			start_date: "2/12/2021",
			color: "Maroon",
		},
		{
			id: "13",
			name: "Florida Garces",
			position: "Web Developer IV",
			company: "Gaylord, Pacocha and Baumbach",
			country: "Poland",
			start_date: "5/31/2020",
			color: "Purple",
		},
		{
			id: "14",
			name: "Maribeth Popping",
			position: "Analyst Programmer",
			company: "Deckow-Pouros",
			country: "Portugal",
			start_date: "4/27/2021",
			color: "Aquamarine",
		},
		{
			id: "15",
			name: "Moritz Dryburgh",
			position: "Dental Hygienist",
			company: "Schiller, Cole and Hackett",
			country: "Sri Lanka",
			start_date: "8/8/2020",
			color: "Crimson",
		},
		{
			id: "16",
			name: "Reid Semiras",
			position: "Teacher",
			company: "Sporer, Sipes and Rogahn",
			country: "Poland",
			start_date: "7/30/2020",
			color: "Green",
		},
		{
			id: "17",
			name: "Alec Lethby",
			position: "Teacher",
			company: "Reichel, Glover and Hamill",
			country: "China",
			start_date: "2/28/2021",
			color: "Khaki",
		},
		{
			id: "18",
			name: "Aland Wilber",
			position: "Quality Control Specialist",
			company: "Kshlerin, Rogahn and Swaniawski",
			country: "Czech Republic",
			start_date: "9/29/2020",
			color: "Purple",
		},
		{
			id: "19",
			name: "Teddie Duerden",
			position: "Staff Accountant III",
			company: "Pouros, Ullrich and Windler",
			country: "France",
			start_date: "10/27/2020",
			color: "Aquamarine",
		},
		{
			id: "20",
			name: "Lorelei Blackstone",
			position: "Data Coordiator",
			company: "Witting, Kutch and Greenfelder",
			country: "Kazakhstan",
			start_date: "6/3/2020",
			color: "Red",
		},
	]);

	return (
		<div className="overflow-y-auto w-full h-full  grid grid-rows-[0.1fr_1fr] ">
			<HeaderTable />
			<ListTable />
		</div>
	);
}
