import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/modules/core/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="size-full grid grid-cols-[0.5fr_1fr] grid-rows-[0.15fr_1fr] bg-primary/80 ">
					<NavBar />
					{children}
				</div>
			</body>
		</html>
	);
}
